import { Box, Button } from '@mui/material'
import Head from 'next/head'
import { useEffect, useState } from 'react'
import { isLoggedIn } from '../config/utils'
import styles from '../styles/Landing.module.css'
import Image from 'next/image'
import poster from '../static/poster.png'
import Home from '../components/Home/Home'

export default function Landing() {

  const [ loginStatus , setLoggedIn ] = useState(false);

  useEffect(() => {
    setLoggedIn(isLoggedIn())
  },[])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {
        loginStatus ? 
        <Home />
        :
        <>
          <div className={styles.cls_HomeWrapper}>
            <div className={styles.cls_ImageWrapper}>
              <Image
                src={poster}
                alt="Hackathon"
                width={800}
              />
            </div>
            <Box my={2} className = {styles.cls_BtnWrap}>
              <Button
                className = "cls_Btn"
                color="primary"
                fullWidth
                size="large"
                type="submit"
                variant="contained"
                href = "/login"
              >
                Sign In to Continue
              </Button>
            </Box>
          </div>
        </>
      }
    </div>
  )
}
